# This dockerfile is meant to be personalized, and serves as a template and demonstration.
# Modify it directly, but it is recommended to copy this dockerfile into a new build context (directory),
# modify to taste and modify docker-compose.yml.template to build and run it.

# It is recommended to control docker containers through 'docker-compose' https://docs.docker.com/compose/
# Docker compose depends on a .yml file to control container sets
# rocm-setup.sh can generate a useful docker-compose .yml file
# `docker-compose run --rm <rocm-terminal>`

# If it is desired to run the container manually through the docker command-line, the following is an example
# 'docker run -it --rm -v [host/directory]:[container/directory]:ro <user-name>/<project-name>'.

FROM ubuntu:22.04
MAINTAINER musk <musk@sietium.com>

# Initialize the image
# Modify to pre-install dev tools and ROCm packages
ARG ROCM_VERSION=5.7
ARG AMDGPU_VERSION=5.7

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl gnupg && \
  curl -sL http://repo.radeon.com/rocm/rocm.gpg.key | apt-key add - && \
  printf "deb [arch=amd64] https://repo.radeon.com/rocm/apt/$ROCM_VERSION/ jammy main" | tee /etc/apt/sources.list.d/rocm.list && \
  printf "deb [arch=amd64] https://repo.radeon.com/amdgpu/$AMDGPU_VERSION/ubuntu jammy main" | tee /etc/apt/sources.list.d/amdgpu.list && \
  apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  sudo \
  libelf1 \
  libelf-dev \
  libnuma-dev \
  net-tools \
  build-essential \
  git \
  vim-nox \
  cmake \
  cmake-curses-gui \
  ninja-build \
  libdrm-dev \
  zlib1g-dev \
  libudev-dev \
  pciutils \
  pkg-config \
  libsqlite3-dev \
  libbz2-dev \
  libtinfo-dev \
  libfile-basedir-perl \
  kmod \
  gdb \
  libpci3 \
  libpci-dev \
  libx11-dev \
  mesa-common-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev\
  doxygen \
  unzip \
  libpciaccess-dev \
  libdw-dev \
  libfmt-dev \
  file \
  python3 \
  python3-dev \
  python3-pip &&\
  rm -rf /var/lib/apt/lists/* && \
  pip3 install cppheaderparser && \
  apt-get clean

# Grant members of 'sudo' group passwordless privileges
# Comment out to require sudo
COPY sudo-nopasswd /etc/sudoers.d/sudo-nopasswd

# This is meant to be used as an interactive developer container
# Create user rocm-user as member of sudo group
# Append /opt/rocm/bin to the system PATH variable
RUN useradd --create-home -G sudo,video --shell /bin/bash rocm-user
#    sed --in-place=.rocm-backup 's|^\(PATH=.*\)"$|\1:/opt/rocm/bin"|' /etc/environment

USER rocm-user
WORKDIR /home/rocm-user
ENV PATH "${PATH}:/opt/rocm/bin"
ENV LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:/opt/rocm/lib"

# The following are optional enhancements for the command-line experience
# Uncomment the following to install a pre-configured vim environment based on http://vim.spf13.com/
# 1.  Sets up an enhanced command line dev environment within VIM
# 2.  Aliases GDB to enable TUI mode by default
#RUN curl -sL https://j.mp/spf13-vim3 | bash && \
#    echo "alias gdb='gdb --tui'\n" >> ~/.bashrc

# Default to a login shell
CMD ["bash", "-l"]
